# Generated by Django 5.2.9 on 2025-12-16 04:21

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Institute",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "head_office_location",
                    models.CharField(
                        help_text="City / address of the head office. Example: Delhi.",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("SUPER_ADMIN", "Super Admin"),
                            ("ADMIN", "Admin"),
                            ("TEACHER", "Teacher"),
                            ("STUDENT", "Student"),
                        ],
                        default="STUDENT",
                        help_text="Role of the user in the system.",
                        max_length=20,
                    ),
                ),
                (
                    "teacher_code",
                    models.CharField(
                        blank=True,
                        help_text="Unique / readable code for a teacher. Example: 'TCH-001', 'PHY-TEACHER-01'. You can use this code on ID cards, timetables, etc.",
                        max_length=50,
                    ),
                ),
                (
                    "teacher_subjects",
                    models.CharField(
                        blank=True,
                        help_text="Subjects that the teacher handles, stored as plain text. Example: 'Physics', or 'Physics, Chemistry', etc.",
                        max_length=255,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Center",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the center. Example: 'Allen - Jaipur Center'.",
                        max_length=255,
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        help_text="City where this center is located.", max_length=100
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True, help_text="Optional full address of the center."
                    ),
                ),
                (
                    "admins",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Users who are admins of this center.",
                        related_name="admin_centers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "institute",
                    models.ForeignKey(
                        help_text="Parent institute of this center.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="centers",
                        to="account.institute",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="user",
            name="center",
            field=models.ForeignKey(
                blank=True,
                help_text="Center to which the user belongs (if applicable).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="account.center",
            ),
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Program name, e.g. 'Super 30', 'Only Board'.",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional detailed description of the program.",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Optional category for grouping programs.",
                        max_length=100,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Programs can be deactivated instead of deleting.",
                    ),
                ),
                (
                    "center",
                    models.ForeignKey(
                        help_text="Center where this program is offered.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programs",
                        to="account.center",
                    ),
                ),
            ],
            options={
                "ordering": ["center__name", "name"],
                "unique_together": {("center", "name")},
            },
        ),
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Short unique-like code for this batch. Example: 'S30-A-2025'.",
                        max_length=50,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Batch name, e.g. 'Super 30 - Batch A (2025)'.",
                        max_length=255,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, help_text="Optional batch start date.", null=True
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, help_text="Optional batch end date.", null=True
                    ),
                ),
                (
                    "teachers",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Teachers assigned to this batch.",
                        related_name="teaching_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        help_text="Program under which this batch runs.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="account.program",
                    ),
                ),
            ],
            options={
                "ordering": ["program__name", "name"],
                "unique_together": {("program", "name")},
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("DROPPED", "Dropped"),
                        ],
                        default="ACTIVE",
                        help_text="Current enrollment status of the student in this batch.",
                        max_length=20,
                    ),
                ),
                (
                    "joined_on",
                    models.DateField(
                        auto_now_add=True,
                        help_text="Date when the student joined this batch.",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        help_text="Batch into which the student is enrolled.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="account.batch",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        help_text="User with role=STUDENT enrolled in this batch.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("student", "batch")},
            },
        ),
    ]
