# Generated by Django 5.2.9 on 2025-12-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="teacher_employee_id",
            field=models.CharField(
                blank=True,
                help_text="Official employee id of the teacher. Example: 'EMP-00123'.",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="teacher_code",
            field=models.CharField(
                blank=True,
                help_text="Readable code for a teacher. Example values from your sheet: 'AK-CAP', 'BTDS', etc.",
                max_length=50,
            ),
        ),
    ]
