# Generated by Django 5.2.9 on 2025-12-16 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_user_teacher_employee_id_alter_user_teacher_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Primary contact phone number of the user.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                help_text="Optional profile image of the user.",
                null=True,
                upload_to="profiles/",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("SUPER_ADMIN", "Super Admin"),
                    ("ADMIN", "Admin"),
                    ("TEACHER", "Teacher"),
                    ("STUDENT", "Student"),
                    ("STAFF", "Staff"),
                ],
                default="STUDENT",
                help_text="Role of the user in the system.",
                max_length=20,
            ),
        ),
    ]
