# Generated by Django 5.2.9 on 2025-12-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_user_phone_number_user_profile_image_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="default_available_slots",
            field=models.JSONField(
                blank=True,
                help_text="Optional default weekly slot availability for this teacher. Use this as a template when creating TeacherSlotAvailability rows for a new timetable.",
                null=True,
            ),
        ),
    ]
