# Generated by Django 5.2.7 on 2025-10-07 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

# Handle optional pgvector import
try:
    import pgvector.django.vector
    PGVECTOR_AVAILABLE = True
except ImportError:
    PGVECTOR_AVAILABLE = False
    # Create a dummy vector field for migration compatibility
    class DummyVectorField(models.TextField):
        def __init__(self, *args, **kwargs):
            # Remove pgvector-specific parameters
            kwargs.pop('dimensions', None)
            kwargs['default'] = ''
            super().__init__(*args, **kwargs)
    
    class VectorField(DummyVectorField):
        pass
    
    pgvector = type('pgvector', (), {
        'django': type('django', (), {
            'vector': type('vector', (), {
                'VectorField': VectorField
            })()
        })()
    })()


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_pattern_section'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionEmbedding',
            fields=[
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='embedding', serialize=False, to='questions.question')),
                ('text_embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('combined_embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('embedding_model', models.CharField(default='text-embedding-ada-002', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'question_embeddings',
                'indexes': [models.Index(fields=['created_at'], name='question_em_created_3a47af_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['user', 'session_id', 'created_at'], name='questions_c_user_id_7e817a_idx')],
            },
        ),
    ]
