# Generated by Django 5.2.7 on 2025-10-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_migrate_question_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_number_in_pattern',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
