# Generated by Django 5.2.7 on 2025-10-18 10:43

import pgvector.django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_add_question_number_in_pattern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionembedding',
            name='combined_embedding',
            field=pgvector.django.VectorField(blank=True, dimensions=1536, null=True),
        ),
        migrations.AlterField(
            model_name='questionembedding',
            name='text_embedding',
            field=pgvector.django.VectorField(dimensions=1536),
        ),
    ]
