# Generated by Django 4.2.25 on 2025-10-29 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_institute_domain_alter_user_institute'),
        ('questions', '0007_alter_questionembedding_combined_embedding_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questiontemplate',
            options={'ordering': ['-is_featured', '-usage_count', 'name']},
        ),
        migrations.AddField(
            model_name='questiontemplate',
            name='category',
            field=models.CharField(choices=[('academic', 'Academic'), ('competitive', 'Competitive Exams'), ('language', 'Language Learning'), ('technical', 'Technical'), ('mathematics', 'Mathematics'), ('science', 'Science'), ('general', 'General Knowledge')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='questiontemplate',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='questiontemplate',
            name='example_question',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='questiontemplate',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_templates', to='accounts.institute'),
        ),
        migrations.AddField(
            model_name='questiontemplate',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questiontemplate',
            name='subject',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='questiontemplate',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='questiontemplate',
            name='topic',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='questiontemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='questiontemplate',
            name='usage_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
