# Generated by Django 4.2.25 on 2025-11-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_add_missing_exam_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_number_in_pattern',
            field=models.IntegerField(blank=True, help_text='Question number within the pattern/subject grouping', null=True),
        ),
    ]
