# Generated by Django 4.2.25 on 2025-11-10 10:48

from django.db import migrations, models, connection


def check_and_add_field(apps, schema_editor):
    """Check if column exists before adding it"""
    Question = apps.get_model('questions', 'Question')
    db_table = Question._meta.db_table
    
    with connection.cursor() as cursor:
        # Check if column exists
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name=%s AND column_name=%s
        """, [db_table, 'question_number_in_pattern'])
        
        exists = cursor.fetchone()
        
        if not exists:
            # Column doesn't exist, add it
            cursor.execute(f"""
                ALTER TABLE {db_table} 
                ADD COLUMN question_number_in_pattern INTEGER NULL
            """)


def reverse_migration(apps, schema_editor):
    """Remove the field if it exists"""
    Question = apps.get_model('questions', 'Question')
    db_table = Question._meta.db_table
    
    with connection.cursor() as cursor:
        # Check if column exists
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name=%s AND column_name=%s
        """, [db_table, 'question_number_in_pattern'])
        
        exists = cursor.fetchone()
        
        if exists:
            # Column exists, remove it
            cursor.execute(f"""
                ALTER TABLE {db_table} 
                DROP COLUMN question_number_in_pattern
            """)


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_add_missing_exam_column'),
    ]

    operations = [
        migrations.RunPython(
            check_and_add_field,
            reverse_migration,
        ),
    ]
