# Generated by Django 4.2.25 on 2025-11-26 10:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import questions.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0014_examproctoring_incidents'),
        ('patterns', '0008_subject_wise_question_numbering'),
        ('questions', '0013_alter_question_unique_together'),
    ]

    operations = [
        # Removed AddField for question_number_in_pattern as it already exists
        # Removed AlterField operations for questionembedding as they're not critical
        migrations.CreateModel(
            name='ExtractionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(help_text='Original filename', max_length=255)),
                ('file_type', models.CharField(help_text='MIME type of uploaded file', max_length=50)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('file_path', models.CharField(help_text='Path to uploaded file', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partially Completed')], db_index=True, default='pending', max_length=20)),
                ('progress_percent', models.IntegerField(default=0, help_text='Extraction progress percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('total_questions_found', models.IntegerField(default=0, help_text='Total questions detected in file')),
                ('questions_extracted', models.IntegerField(default=0, help_text='Questions successfully extracted')),
                ('questions_imported', models.IntegerField(default=0, help_text='Questions successfully imported to exam')),
                ('questions_failed', models.IntegerField(default=0, help_text='Questions that failed extraction or import')),
                ('ai_model_used', models.CharField(default='gemini-1.5-flash', help_text='AI model used for extraction', max_length=100)),
                ('tokens_used', models.IntegerField(default=0, help_text='Total tokens consumed by AI API')),
                ('processing_time_seconds', models.FloatField(blank=True, help_text='Total processing time in seconds', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if extraction failed')),
                ('retry_count', models.IntegerField(default=0, help_text='Number of retry attempts')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(help_text='User who uploaded the file', on_delete=django.db.models.deletion.CASCADE, related_name='extraction_jobs', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(help_text='Exam to import questions into', on_delete=django.db.models.deletion.CASCADE, related_name='extraction_jobs', to='exams.exam')),
                ('pattern', models.ForeignKey(help_text='Pattern structure for organizing questions', on_delete=django.db.models.deletion.CASCADE, related_name='extraction_jobs', to='patterns.exampattern')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='Question text extracted from file')),
                ('question_type', models.CharField(choices=[('single_mcq', 'Single Correct MCQ'), ('multiple_mcq', 'Multiple Correct MCQ'), ('numerical', 'Numerical Questions'), ('subjective', 'Subjective Questions'), ('true_false', 'True/False Questions'), ('fill_blank', 'Fill in the Blanks')], help_text='Type of question', max_length=20)),
                ('options', models.JSONField(blank=True, default=list, help_text='Answer options for MCQ questions')),
                ('correct_answer', models.TextField(help_text='Correct answer or solution')),
                ('solution', models.TextField(blank=True, help_text='Detailed solution explanation')),
                ('explanation', models.TextField(blank=True, help_text='Additional explanation or hints')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', help_text='Question difficulty level', max_length=10)),
                ('confidence_score', models.FloatField(help_text='AI confidence score (0.0 to 1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('requires_review', models.BooleanField(default=False, help_text='Whether question needs manual review')),
                ('suggested_subject', models.CharField(blank=True, help_text='AI-suggested subject for this question', max_length=100)),
                ('suggested_section_id', models.IntegerField(blank=True, help_text='AI-suggested pattern section ID', null=True)),
                ('assigned_subject', models.CharField(blank=True, help_text='User-assigned subject', max_length=100)),
                ('assigned_section_id', models.IntegerField(blank=True, help_text='User-assigned pattern section ID', null=True)),
                ('is_validated', models.BooleanField(default=False, help_text='Whether question passed validation')),
                ('is_imported', models.BooleanField(db_index=True, default=False, help_text='Whether question was imported to exam')),
                ('import_error', models.TextField(blank=True, help_text='Error message if import failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('imported_question', models.ForeignKey(blank=True, help_text='Reference to the imported Question record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extraction_source', to='questions.question')),
                ('job', models.ForeignKey(help_text='Extraction job this question belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='extracted_questions', to='questions.extractionjob')),
            ],
            options={
                'ordering': ['job', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='extractionjob',
            index=models.Index(fields=['exam', 'status'], name='questions_e_exam_id_c4d552_idx'),
        ),
        migrations.AddIndex(
            model_name='extractionjob',
            index=models.Index(fields=['created_by', 'created_at'], name='questions_e_created_a4a478_idx'),
        ),
        migrations.AddIndex(
            model_name='extractedquestion',
            index=models.Index(fields=['job', 'is_imported'], name='questions_e_job_id_8d5758_idx'),
        ),
        migrations.AddIndex(
            model_name='extractedquestion',
            index=models.Index(fields=['job', 'requires_review'], name='questions_e_job_id_c4a31e_idx'),
        ),
    ]
