# Generated by Django 4.2.25 on 2025-11-28 04:54

from django.db import migrations, models
import questions.models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0015_add_detection_reasoning'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extractionjob',
            name='mismatch_analysis',
        ),
        migrations.RemoveField(
            model_name='extractionjob',
            name='subject_distribution',
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='question',
                    name='question_number_in_pattern',
                    field=models.IntegerField(blank=True, help_text='Question number within the pattern/subject grouping', null=True),
                ),
            ],
            database_operations=[],
        ),
        migrations.AlterField(
            model_name='questionembedding',
            name='combined_embedding',
            field=questions.models.VectorField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='questionembedding',
            name='text_embedding',
            field=questions.models.VectorField(default=list),
        ),
    ]
