# Generated by Django 4.2.25 on 2025-11-28 04:56

from django.db import migrations
import questions.models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0016_remove_extractionjob_mismatch_analysis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionembedding',
            name='combined_embedding',
            field=questions.models.VectorField(blank=True, dimensions=1536, null=True),
        ),
        migrations.AlterField(
            model_name='questionembedding',
            name='text_embedding',
            field=questions.models.VectorField(dimensions=1536),
        ),
    ]
