# Generated by Django 4.2.25 on 2025-12-01 11:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0008_subject_wise_question_numbering'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0018_alter_extractionjob_file_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreAnalysisJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(help_text='Original filename', max_length=255)),
                ('file_type', models.CharField(help_text='MIME type of uploaded file', max_length=100)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('file_path', models.CharField(help_text='Path to uploaded file', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('document_type', models.CharField(blank=True, choices=[('questions_with_answers', 'Questions with Answers'), ('questions_only', 'Questions Only'), ('other', 'Other')], help_text='Detected document type', max_length=30)),
                ('document_type_confidence', models.FloatField(default=0.0, help_text='Confidence score for document type detection', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('is_valid_document', models.BooleanField(default=False, help_text='Whether document is valid for question extraction')),
                ('detected_subjects', models.JSONField(blank=True, default=list, help_text='List of subjects detected in document')),
                ('matched_subjects', models.JSONField(blank=True, default=list, help_text='Subjects matched against pattern')),
                ('unmatched_subjects', models.JSONField(blank=True, default=list, help_text='Detected subjects not in pattern')),
                ('subject_question_counts', models.JSONField(blank=True, default=dict, help_text='Estimated question count per subject')),
                ('subject_separated_content', models.JSONField(blank=True, default=dict, help_text='Document content separated by subject')),
                ('total_estimated_questions', models.IntegerField(default=0, help_text='Total estimated questions in document')),
                ('error_message', models.TextField(blank=True, help_text='Error message if analysis failed')),
                ('analysis_reason', models.TextField(blank=True, help_text='Reason for document type classification')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(help_text='User who uploaded the file', on_delete=django.db.models.deletion.CASCADE, related_name='pre_analysis_jobs', to=settings.AUTH_USER_MODEL)),
                ('extraction_job', models.ForeignKey(blank=True, help_text='Extraction job created from this pre-analysis', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_analysis', to='questions.extractionjob')),
                ('pattern', models.ForeignKey(help_text='Pattern to match subjects against', on_delete=django.db.models.deletion.CASCADE, related_name='pre_analysis_jobs', to='patterns.exampattern')),
            ],
            options={
                'verbose_name': 'Pre-Analysis Job',
                'verbose_name_plural': 'Pre-Analysis Jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['pattern', 'status'], name='questions_p_pattern_542f6c_idx'), models.Index(fields=['created_by', 'created_at'], name='questions_p_created_8093e8_idx')],
            },
        ),
    ]
