# Generated by Django 4.2.25 on 2025-12-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0019_preanalysisjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='preanalysisjob',
            name='document_structure',
            field=models.JSONField(blank=True, default=dict, help_text='Detected document structure with sections and question types'),
        ),
    ]
