# Generated by Django 4.2.25 on 2026-01-28 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0017_add_visibility_scope'),
        ('questions', '0021_add_ocr_result_and_preanalysis_link'),
    ]

    operations = [
        # Manually manage the constraint to avoid issues with missing/mismatched existing constraints
        migrations.RunSQL(
            sql="""
            -- Drop existing constraint if it exists (by checking columns)
            DO $$
            DECLARE
                v_constraint_name text;
            BEGIN
                SELECT conname INTO v_constraint_name
                FROM pg_constraint 
                WHERE conrelid = 'questions_question'::regclass 
                AND contype = 'u'
                AND (
                    (confkey @> (SELECT array_agg(attnum) FROM pg_attribute WHERE attrelid = 'questions_question'::regclass AND attname IN ('exam_id', 'question_number')))
                    OR
                    -- Check for exact match of current django unique_together
                    array_to_string(conkey, ',') = (
                        SELECT array_to_string(array_agg(attnum), ',') 
                        FROM pg_attribute 
                        WHERE attrelid = 'questions_question'::regclass 
                        AND attname IN ('exam_id', 'question_number')
                    )
                );

                IF v_constraint_name IS NOT NULL THEN
                    EXECUTE 'ALTER TABLE questions_question DROP CONSTRAINT ' || v_constraint_name;
                END IF;

                -- Add new constraint
                ALTER TABLE questions_question ADD CONSTRAINT questions_question_exam_section_qnum_unique 
                UNIQUE (exam_id, pattern_section_id, question_number);
            END;
            $$;
            """,
            reverse_sql="""
            ALTER TABLE questions_question DROP CONSTRAINT IF EXISTS questions_question_exam_section_qnum_unique;
            -- We don't restore the old one because we're not sure what it was or if it existed
            """
        ),
    ]
