# Generated by Django 4.2.16 on 2026-02-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0018_alter_examproctoring_snapshots_proctoringsnapshot'),
        ('questions', '0022_alter_question_unique_together'),
    ]

    operations = [
        # migrations.AlterUniqueTogether(
        #     name='question',
        #     unique_together={('exam', 'pattern_section_id', 'question_number')},
        # ),
        migrations.AddField(
            model_name='question',
            name='structure',
            field=models.JSONField(blank=True, default=dict, help_text='Defines nested sub-questions or internal choices for complex questions'),
        ),
    ]
