# Generated by Django 4.2.25 on 2026-02-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0019_add_exam_mode_fields"),
        ("questions", "0024_add_detected_sections_per_subject"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(
                    name="question",
                    unique_together={("exam", "pattern_section_id", "question_number")},
                ),
            ],
            database_operations=[]  # Constraint was already manually added/modified in 0022
        ),
        migrations.AddField(
            model_name="extractedquestion",
            name="structure",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Defines nested sub-questions or internal choices for complex questions",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="correct_answer",
            field=models.TextField(blank=True),
        ),
    ]
