# Generated by Django 4.2.7 on 2026-02-17 07:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0025_alter_question_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extractedquestion",
            name="confidence_score",
            field=models.FloatField(
                blank=True,
                help_text="AI confidence score (0.0 to 1.0)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="extractedquestion",
            name="correct_answer",
            field=models.TextField(
                blank=True, help_text="Correct answer or solution", null=True
            ),
        ),
        migrations.AlterField(
            model_name="extractedquestion",
            name="options",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Answer options for MCQ questions",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="extractedquestion",
            name="question_text",
            field=models.TextField(
                blank=True, help_text="Question text extracted from file", null=True
            ),
        ),
        migrations.AlterField(
            model_name="extractedquestion",
            name="question_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("single_mcq", "Single Correct MCQ"),
                    ("multiple_mcq", "Multiple Correct MCQ"),
                    ("numerical", "Numerical Questions"),
                    ("subjective", "Subjective Questions"),
                    ("true_false", "True/False Questions"),
                    ("fill_blank", "Fill in the Blanks"),
                ],
                help_text="Type of question",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="extractedquestion",
            name="structure",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Defines nested sub-questions or internal choices for complex questions",
                null=True,
            ),
        ),
    ]
