# Generated by Django 4.2.7 on 2026-02-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0026_alter_extractedquestion_confidence_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="extractedquestion",
            name="images_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Internal mapping of image IDs to temporary storage paths",
            ),
        ),
    ]
