# Generated by Django 4.2.25 on 2026-03-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0027_extractedquestion_images_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractedquestion',
            name='solution',
            field=models.TextField(blank=True, help_text='Detailed solution explanation', null=True),
        ),
    ]
