# Generated by Django 4.2.25 on 2026-03-12 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0028_alter_chathistory_user_and_more'),
        ('questions', '0029_fix_solution_null'),
    ]

    operations = [
    ]
