# Generated by Django 4.2.7 on 2026-03-11 09:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0028_alter_chathistory_user_and_more"),
        ("questions", "0029_fix_solution_null"),
    ]

    operations = []
