# Generated by Django 4.2.7 on 2026-03-12 06:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0030_merge_20260311_0948"),
        ("questions", "0030_merge_20260312_0240"),
    ]

    operations = []
