# Generated by Django 4.2.25 on 2026-03-12 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0030_merge_20260311_1456'),
        ('questions', '0031_merge_20260312_0621'),
    ]

    operations = [
    ]
