# Generated by Django 4.2.16 on 2026-02-05 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0019_add_exam_mode_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='OMRSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='omr_sheets/')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Layout coordinates from OMR generator for evaluation')),
                ('candidate_fields', models.JSONField(blank=True, default=list, help_text='Candidate identification fields (roll number, center code, etc.)')),
                ('question_config', models.JSONField(blank=True, default=list, help_text='Question configuration used for generation')),
                ('status', models.CharField(choices=[('pending', 'Pending Generation'), ('generating', 'Generating'), ('generated', 'Generated'), ('failed', 'Generation Failed')], default='pending', max_length=20)),
                ('generation_error', models.TextField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=True, help_text='Primary OMR sheet for the exam')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='omr_sheets', to='exams.exam')),
            ],
            options={
                'verbose_name': 'OMR Sheet',
                'verbose_name_plural': 'OMR Sheets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OMRSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_files', models.JSONField(default=list, help_text='List of uploaded scanned image/PDF paths')),
                ('status', models.CharField(choices=[('pending', 'Pending Evaluation'), ('processing', 'Processing'), ('evaluated', 'Evaluated'), ('failed', 'Evaluation Failed')], default='pending', max_length=20)),
                ('evaluation_error', models.TextField(blank=True, null=True)),
                ('extracted_responses', models.JSONField(blank=True, default=dict, help_text='Responses extracted from the scanned OMR sheet')),
                ('candidate_info', models.JSONField(blank=True, default=dict, help_text='Candidate identification info extracted from OMR')),
                ('evaluation_results', models.JSONField(blank=True, default=dict, help_text='Full evaluation results including score and question details')),
                ('annotated_pdf', models.FileField(blank=True, help_text='Annotated OMR sheet with marks/ticks', null=True, upload_to='omr_results/')),
                ('results_json', models.FileField(blank=True, help_text='JSON file with detailed results', null=True, upload_to='omr_results/')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_score', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='omr_submissions', to='exams.examattempt')),
                ('omr_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='omr.omrsheet')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='omr_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OMR Submission',
                'verbose_name_plural': 'OMR Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='AnswerKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(default=dict, help_text='Answer key mapping question fields to correct answers and marks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_answer_keys', to=settings.AUTH_USER_MODEL)),
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer_key', to='exams.exam')),
            ],
            options={
                'verbose_name': 'Answer Key',
                'verbose_name_plural': 'Answer Keys',
            },
        ),
    ]
