# Generated by Django 4.2.7 on 2026-03-10 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("omr", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answerkey",
            name="created_by",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_answer_keys",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="omrsubmission",
            name="student",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="omr_submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
