# Generated by Django 5.2.7 on 2025-10-04 06:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatternTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(help_text='e.g., Engineering, Medical, Competitive', max_length=100)),
                ('total_questions', models.IntegerField()),
                ('total_duration', models.IntegerField()),
                ('total_marks', models.IntegerField()),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExamPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('total_questions', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)])),
                ('total_duration', models.IntegerField(help_text='Duration in minutes', validators=[django.core.validators.MinValueValidator(1)])),
                ('total_marks', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_patterns', to=settings.AUTH_USER_MODEL)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_patterns', to='accounts.institute')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('name', 'institute')},
            },
        ),
        migrations.CreateModel(
            name='PatternSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice Questions'), ('numerical', 'Numerical Questions'), ('subjective', 'Subjective Questions'), ('true_false', 'True/False Questions'), ('fill_blank', 'Fill in the Blanks')], max_length=20)),
                ('start_question', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('end_question', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('marks_per_question', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('negative_marking', models.DecimalField(decimal_places=2, default=0.25, help_text='Negative marks for wrong answer', max_digits=3)),
                ('min_questions_to_attempt', models.IntegerField(default=0, help_text='Minimum questions student must attempt')),
                ('is_compulsory', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='patterns.exampattern')),
            ],
            options={
                'ordering': ['order', 'start_question'],
                'unique_together': {('pattern', 'start_question', 'end_question')},
            },
        ),
    ]
