# Generated by Django 5.2.7 on 2025-10-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0002_add_subject_model_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patternsection',
            name='negative_marking',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Fixed negative marks deducted per incorrect answer (e.g., 1.00)', max_digits=4),
        ),
    ]
