# Generated by Django 5.2.7 on 2025-10-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0003_alter_patternsection_negative_marking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patternsection',
            name='min_questions_to_attempt',
            field=models.IntegerField(default=5, help_text='Minimum questions student must attempt'),
        ),
    ]
