# Generated by Django 5.2.7 on 2025-10-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0004_alter_patternsection_min_questions_to_attempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patternsection',
            name='question_type',
            field=models.CharField(choices=[('single_mcq', 'Single Correct MCQ'), ('multiple_mcq', 'Multiple Correct MCQ'), ('numerical', 'Numerical Questions'), ('subjective', 'Subjective Questions'), ('true_false', 'True/False Questions'), ('fill_blank', 'Fill in the Blanks')], max_length=20),
        ),
    ]
