# Generated by Django 4.2.25 on 2025-10-29 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_alter_questiontemplate_options_and_more'),
        ('patterns', '0006_migrate_question_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampattern',
            name='pattern_type',
            field=models.CharField(choices=[('fixed', 'Fixed Questions'), ('template', 'Template Only'), ('hybrid', 'Hybrid (Mixed)')], default='fixed', max_length=20),
        ),
        migrations.AddField(
            model_name='patternsection',
            name='fixed_questions',
            field=models.JSONField(blank=True, default=list, help_text='List of fixed question IDs for fixed sections'),
        ),
        migrations.AddField(
            model_name='patternsection',
            name='question_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pattern_sections', to='questions.questionbank'),
        ),
        migrations.AddField(
            model_name='patternsection',
            name='section_type',
            field=models.CharField(choices=[('fixed', 'Fixed Questions'), ('template', 'Template Selection'), ('random', 'Random Selection')], default='fixed', max_length=20),
        ),
        migrations.AddField(
            model_name='patternsection',
            name='selection_criteria',
            field=models.JSONField(blank=True, default=dict, help_text='Criteria for question selection (difficulty, topic, etc.)'),
        ),
    ]
