# Generated by Django 4.2.25 on 2025-11-06 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0007_exampattern_pattern_type_and_more'),
    ]

    operations = [
        # Update ordering to group by subject first
        migrations.AlterModelOptions(
            name='patternsection',
            options={'ordering': ['subject', 'order', 'start_question']},
        ),
        # Update unique_together to allow same question ranges across different subjects
        # Now uniqueness is enforced per pattern + subject + question range
        migrations.AlterUniqueTogether(
            name='patternsection',
            unique_together={('pattern', 'subject', 'start_question', 'end_question')},
        ),
    ]
