# Generated by Django 4.2.25 on 2026-01-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0008_subject_wise_question_numbering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
