# Generated by Django 4.2.16 on 2026-02-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0009_alter_subject_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='patternsection',
            name='question_configurations',
            field=models.JSONField(blank=True, default=dict, help_text='Per-question configuration overrides (e.g. nested structure for subjective questions)'),
        ),
    ]
