# Generated by Django 4.2.7 on 2026-02-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patterns", "0010_patternsection_question_configurations"),
    ]

    operations = [
        migrations.AddField(
            model_name="exampattern",
            name="exam_mode",
            field=models.CharField(
                choices=[
                    ("online", "Online Exam"),
                    ("offline_omr", "Offline OMR-Based"),
                    ("offline_subjective", "Offline Subjective"),
                ],
                default="online",
                help_text="Default exam mode for exams using this pattern",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="exampattern",
            name="omr_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Default OMR configuration (candidate fields, etc.)",
            ),
        ),
    ]
