# Generated by Django 4.2.7 on 2026-03-10 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0013_institute_db_host_institute_db_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("patterns", "0011_exampattern_exam_mode_exampattern_omr_config"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exampattern",
            name="created_by",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_patterns",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="exampattern",
            name="institute",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exam_patterns",
                to="accounts.institute",
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="institute",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to="accounts.institute",
            ),
        ),
    ]
