# Generated by Django 5.2.7 on 2025-10-04 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_institutes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='institute',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description of the institute'),
        ),
        migrations.AddField(
            model_name='institute',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Whether the institute is verified by super admin'),
        ),
        migrations.AddField(
            model_name='institute',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='institute_logos/'),
        ),
        migrations.AddField(
            model_name='institute',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='InstituteInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('institute_admin', 'Institute Admin'), ('exam_admin', 'Exam Admin'), ('teacher', 'Teacher'), ('student', 'Student')], default='student', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('message', models.TextField(blank=True, help_text='Optional message to include with invitation')),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='accounts.institute')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_institute_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('institute', 'email')},
            },
        ),
    ]
