# Generated by Django 5.2.7 on 2025-10-07 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_institute_created_by_institute_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='domain',
            field=models.CharField(blank=True, help_text="Optional email domain (e.g., 'university.edu')", max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.institute'),
        ),
    ]
