# Generated by Django 4.2.7 on 2025-12-17 06:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_institute_domain_alter_user_institute"),
    ]

    operations = [
        migrations.CreateModel(
            name="Center",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the center. Example: 'Allen - Jaipur Center'.",
                        max_length=255,
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        help_text="City where this center is located.", max_length=100
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True, help_text="Optional full address of the center."
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
        migrations.AddField(
            model_name="institute",
            name="head_office_location",
            field=models.CharField(
                blank=True,
                help_text="City / address of the head office. Example: Delhi.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="default_available_slots",
            field=models.JSONField(
                blank=True,
                help_text="Optional default weekly slot availability for this teacher.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Primary contact phone number (timetable system).",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                help_text="Optional profile image (timetable system).",
                null=True,
                upload_to="profiles/",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="teacher_code",
            field=models.CharField(
                blank=True,
                help_text="Readable code for a teacher. Example: 'AK-CAP', 'BTDS', etc.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="teacher_employee_id",
            field=models.CharField(
                blank=True,
                help_text="Official employee id of the teacher. Example: 'EMP-00123'.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="teacher_subjects",
            field=models.CharField(
                blank=True,
                help_text="Subjects that the teacher handles. Example: 'Physics', or 'Physics, Chemistry'.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="institute",
            name="contact_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AlterField(
            model_name="institute",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="institute",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("super_admin", "Super Admin"),
                    ("institute_admin", "Institute Admin"),
                    ("exam_admin", "Exam Admin"),
                    ("teacher", "Teacher"),
                    ("student", "Student"),
                    ("ADMIN", "Center Admin"),
                    ("STAFF", "Staff"),
                ],
                default="student",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Program name, e.g. 'Super 30', 'Only Board'.",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional detailed description of the program.",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Optional category for grouping programs.",
                        max_length=100,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Programs can be deactivated instead of deleting.",
                    ),
                ),
                (
                    "center",
                    models.ForeignKey(
                        help_text="Center where this program is offered.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programs",
                        to="accounts.center",
                    ),
                ),
            ],
            options={
                "ordering": ["center__name", "name"],
                "unique_together": {("center", "name")},
            },
        ),
        migrations.AddField(
            model_name="center",
            name="admins",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who are admins of this center.",
                related_name="admin_centers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="center",
            name="institute",
            field=models.ForeignKey(
                help_text="Parent institute of this center.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="centers",
                to="accounts.institute",
            ),
        ),
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Short unique-like code for this batch. Example: 'S30-A-2025'.",
                        max_length=50,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Batch name, e.g. 'Super 30 - Batch A (2025)'.",
                        max_length=255,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, help_text="Optional batch start date.", null=True
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, help_text="Optional batch end date.", null=True
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        help_text="Program under which this batch runs.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="accounts.program",
                    ),
                ),
                (
                    "teachers",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Teachers assigned to this batch.",
                        related_name="teaching_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["program__name", "name"],
                "unique_together": {("program", "name")},
            },
        ),
        migrations.AddField(
            model_name="user",
            name="center",
            field=models.ForeignKey(
                blank=True,
                help_text="Center to which the user belongs (timetable system).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="accounts.center",
            ),
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("DROPPED", "Dropped"),
                        ],
                        default="ACTIVE",
                        help_text="Current enrollment status of the student in this batch.",
                        max_length=20,
                    ),
                ),
                (
                    "joined_on",
                    models.DateField(
                        auto_now_add=True,
                        help_text="Date when the student joined this batch.",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        help_text="Batch into which the student is enrolled.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="accounts.batch",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        help_text="User with role=STUDENT enrolled in this batch.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("student", "batch")},
            },
        ),
    ]
