# Generated by Django 4.2.25 on 2025-12-18 04:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_center_alter_user_options_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE accounts_institute ADD COLUMN IF NOT EXISTS head_office_location VARCHAR(255)",
            reverse_sql="ALTER TABLE accounts_institute DROP COLUMN IF EXISTS head_office_location",
        ),
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.columns 
                        WHERE table_name='accounts_user' AND column_name='center_id'
                    ) THEN
                        ALTER TABLE accounts_user 
                        ADD COLUMN center_id UUID REFERENCES accounts_center(id) ON DELETE SET NULL;
                    END IF;
                END $$;
            """,
            reverse_sql="ALTER TABLE accounts_user DROP COLUMN IF EXISTS center_id",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE accounts_user ADD COLUMN IF NOT EXISTS default_available_slots JSONB",
            reverse_sql="ALTER TABLE accounts_user DROP COLUMN IF EXISTS default_available_slots",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE accounts_user ADD COLUMN IF NOT EXISTS phone_number VARCHAR(20)",
            reverse_sql="ALTER TABLE accounts_user DROP COLUMN IF EXISTS phone_number",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE accounts_user ADD COLUMN IF NOT EXISTS profile_image VARCHAR(100)",
            reverse_sql="ALTER TABLE accounts_user DROP COLUMN IF EXISTS profile_image",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE accounts_user ADD COLUMN IF NOT EXISTS teacher_code VARCHAR(50)",
            reverse_sql="ALTER TABLE accounts_user DROP COLUMN IF EXISTS teacher_code",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE accounts_user ADD COLUMN IF NOT EXISTS teacher_employee_id VARCHAR(50)",
            reverse_sql="ALTER TABLE accounts_user DROP COLUMN IF EXISTS teacher_employee_id",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE accounts_user ADD COLUMN IF NOT EXISTS teacher_subjects VARCHAR(255)",
            reverse_sql="ALTER TABLE accounts_user DROP COLUMN IF EXISTS teacher_subjects",
        ),
        migrations.AlterField(
            model_name='center',
            name='address',
            field=models.TextField(blank=True, help_text='Optional full address of the center.', null=True),
        ),
        migrations.AlterField(
            model_name='institute',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='institute',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='institute',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='institute',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description of the institute', null=True),
        ),
        migrations.AlterField(
            model_name='institute',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='institute',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.TextField(blank=True, help_text='Optional detailed description of the program.', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
