# Generated by Django 4.2.7 on 2025-12-18 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_institute_head_office_location_user_center_and_more"),
    ]

    operations = [
        # All these fields were already added in migration 0005 using RunSQL with IF NOT EXISTS
        # This migration just ensures they exist and handles the category field alteration
        migrations.RunSQL(
            sql="ALTER TABLE accounts_institute ADD COLUMN IF NOT EXISTS head_office_location VARCHAR(255)",
            reverse_sql="ALTER TABLE accounts_institute DROP COLUMN IF EXISTS head_office_location",
        ),
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.columns 
                        WHERE table_name='accounts_user' AND column_name='center_id'
                    ) THEN
                        ALTER TABLE accounts_user 
                        ADD COLUMN center_id UUID REFERENCES accounts_center(id) ON DELETE SET NULL;
                    END IF;
                END $$;
            """,
            reverse_sql="ALTER TABLE accounts_user DROP COLUMN IF EXISTS center_id",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE accounts_user ADD COLUMN IF NOT EXISTS default_available_slots JSONB",
            reverse_sql="ALTER TABLE accounts_user DROP COLUMN IF EXISTS default_available_slots",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE accounts_user ADD COLUMN IF NOT EXISTS phone_number VARCHAR(20)",
            reverse_sql="ALTER TABLE accounts_user DROP COLUMN IF EXISTS phone_number",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE accounts_user ADD COLUMN IF NOT EXISTS profile_image VARCHAR(100)",
            reverse_sql="ALTER TABLE accounts_user DROP COLUMN IF EXISTS profile_image",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE accounts_user ADD COLUMN IF NOT EXISTS teacher_code VARCHAR(50)",
            reverse_sql="ALTER TABLE accounts_user DROP COLUMN IF EXISTS teacher_code",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE accounts_user ADD COLUMN IF NOT EXISTS teacher_employee_id VARCHAR(50)",
            reverse_sql="ALTER TABLE accounts_user DROP COLUMN IF EXISTS teacher_employee_id",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE accounts_user ADD COLUMN IF NOT EXISTS teacher_subjects VARCHAR(255)",
            reverse_sql="ALTER TABLE accounts_user DROP COLUMN IF EXISTS teacher_subjects",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE accounts_program ALTER COLUMN category DROP NOT NULL",
            reverse_sql="-- Reversible if needed",
        ),
    ]
