# Generated by Django 4.2.7 on 2025-12-18 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_institute_head_office_location_user_center_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="batch",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="institute",
            name="head_office_location",
            field=models.CharField(
                blank=True,
                help_text="City / address of the head office. Example: Delhi.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="center",
            field=models.ForeignKey(
                blank=True,
                help_text="Center to which the user belongs (timetable system).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="accounts.center",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="default_available_slots",
            field=models.JSONField(
                blank=True,
                help_text="Optional default weekly slot availability for this teacher.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Primary contact phone number (timetable system).",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                help_text="Optional profile image (timetable system).",
                null=True,
                upload_to="profiles/",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="teacher_code",
            field=models.CharField(
                blank=True,
                help_text="Readable code for a teacher. Example: 'AK-CAP', 'BTDS', etc.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="teacher_employee_id",
            field=models.CharField(
                blank=True,
                help_text="Official employee id of the teacher. Example: 'EMP-00123'.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="teacher_subjects",
            field=models.CharField(
                blank=True,
                help_text="Subjects that the teacher handles. Example: 'Physics', or 'Physics, Chemistry'.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="batch",
            name="program",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional program under which this batch runs.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="batches",
                to="accounts.program",
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="category",
            field=models.CharField(
                blank=True,
                help_text="Optional category for grouping programs.",
                max_length=100,
                null=True,
            ),
        ),
    ]
