# Generated by Django 4.2.16 on 2026-01-21 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_make_batch_program_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('institute_admin', 'Institute Admin'), ('exam_admin', 'Exam Admin'), ('teacher', 'Teacher'), ('student', 'Student'), ('ADMIN', 'Center Admin'), ('STAFF', 'Staff'), ('manager', 'Manager')], default='student', max_length=20),
        ),
        migrations.CreateModel(
            name='DeviceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_fingerprint', models.CharField(db_index=True, help_text='Unique identifier for the device based on browser and hardware characteristics', max_length=255, unique=True)),
                ('device_type', models.CharField(help_text='Type of device: mobile, desktop, tablet', max_length=50)),
                ('browser', models.CharField(help_text='Browser name and version', max_length=100)),
                ('os', models.CharField(help_text='Operating system name and version', max_length=100)),
                ('screen_resolution', models.CharField(help_text='Screen resolution (e.g., 1920x1080)', max_length=20)),
                ('timezone', models.CharField(help_text="User's timezone", max_length=50)),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the device')),
                ('user_agent', models.TextField(help_text='Full user agent string from the browser')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this session is currently active')),
                ('last_activity', models.DateTimeField(auto_now=True, help_text='Timestamp of last activity on this session')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this session was created')),
                ('expires_at', models.DateTimeField(help_text='When this session expires (24 hours from last activity)')),
                ('user', models.ForeignKey(help_text='User associated with this device session', on_delete=django.db.models.deletion.CASCADE, related_name='device_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Device Session',
                'verbose_name_plural': 'Device Sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='accounts_de_user_id_4f7fa7_idx'), models.Index(fields=['device_fingerprint'], name='accounts_de_device__77f0c0_idx'), models.Index(fields=['expires_at'], name='accounts_de_expires_3b1dfb_idx')],
            },
        ),
    ]
