# Generated by Django 4.2.16 on 2026-02-05 20:11

from django.db import migrations, models
import django.db.models.deletion


def populate_program_institute(apps, schema_editor):
    """
    Populate the institute field on Program from the center's institute.
    Also populate the center field on Batch from the program's center.
    """
    Program = apps.get_model('accounts', 'Program')
    Batch = apps.get_model('accounts', 'Batch')
    
    # For each program, set institute from its center's institute
    for program in Program.objects.select_related('center__institute').all():
        if program.center and program.center.institute:
            program.institute_id = program.center.institute_id
            program.save(update_fields=['institute'])
    
    # For each batch with a program, set center from the program's center
    for batch in Batch.objects.select_related('program__center').filter(program__isnull=False):
        if batch.program and hasattr(batch.program, 'center') and batch.program.center:
            batch.center_id = batch.program.center_id
            batch.save(update_fields=['center'])


def reverse_populate(apps, schema_editor):
    """
    Reverse: populate center field on Program from the batch's center or first center of institute.
    """
    Program = apps.get_model('accounts', 'Program')
    Center = apps.get_model('accounts', 'Center')
    
    for program in Program.objects.select_related('institute').all():
        if program.institute:
            # Get first center of the institute
            first_center = Center.objects.filter(institute_id=program.institute_id).first()
            if first_center:
                program.center_id = first_center.id
                program.save(update_fields=['center'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_role_activitylog'),
    ]

    operations = [
        # Step 1: Add the new fields first (keeping center on Program for now)
        migrations.AddField(
            model_name='batch',
            name='center',
            field=models.ForeignKey(blank=True, help_text='Center where this batch runs.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='accounts.center'),
        ),
        migrations.AddField(
            model_name='program',
            name='institute',
            field=models.ForeignKey(blank=True, help_text='Institute where this program is offered.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='accounts.institute'),
        ),
        
        # Step 2: Run data migration to populate institute from center
        migrations.RunPython(populate_program_institute, reverse_populate),
        
        # Step 3: Update batch program field
        migrations.AlterField(
            model_name='batch',
            name='program',
            field=models.ForeignKey(blank=True, help_text='Program under which this batch runs (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='accounts.program'),
        ),
        
        # Step 4: Update meta options and constraints
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['center__name', 'program__name', 'name']},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['institute__name', 'name']},
        ),
        migrations.AlterUniqueTogether(
            name='program',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='program',
            unique_together={('institute', 'name')},
        ),
        
        # Step 5: Remove the old center field from Program
        migrations.RemoveField(
            model_name='program',
            name='center',
        ),
    ]
