# Generated by Django 4.2.16 on 2026-02-05 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_restructure_program_batch_hierarchy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='institute',
            field=models.ForeignKey(help_text='Institute where this program is offered.', on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='accounts.institute'),
        ),
    ]
