# Generated by Django 4.2.7 on 2026-03-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_fix_batch_program_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="institute",
            name="db_host",
            field=models.CharField(
                blank=True, default="localhost", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="institute",
            name="db_name",
            field=models.CharField(
                blank=True,
                help_text="Specific database name for this institute",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="institute",
            name="db_password",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="institute",
            name="db_port",
            field=models.CharField(
                blank=True, default="5432", max_length=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="institute",
            name="db_user",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
