# Generated by Django 4.2.7 on 2026-03-11 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0013_institute_db_host_institute_db_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserInstituteMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("super_admin", "Super Admin"),
                            ("institute_admin", "Institute Admin"),
                            ("exam_admin", "Exam Admin"),
                            ("teacher", "Teacher"),
                            ("student", "Student"),
                            ("admin", "Center Admin"),
                            ("staff", "Staff"),
                            ("manager", "Manager"),
                        ],
                        default="student",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "institute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="accounts.institute",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Institute Membership",
                "verbose_name_plural": "User Institute Memberships",
                "unique_together": {("user", "institute")},
            },
        ),
        migrations.AddField(
            model_name="user",
            name="institutes",
            field=models.ManyToManyField(
                blank=True,
                related_name="associated_users",
                through="accounts.UserInstituteMembership",
                to="accounts.institute",
            ),
        ),
    ]
