# Generated by Django 4.2.7 on 2026-03-11 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0014_userinstitutemembership_user_institutes"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinstitutemembership",
            name="center",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.center",
            ),
        ),
        migrations.AddField(
            model_name="userinstitutemembership",
            name="teacher_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
