# Generated by Django 4.2.25 on 2026-03-12 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0015_userinstitutemembership_center_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="center",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional center where this program is specifically offered.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="programs",
                to="accounts.center",
            ),
        ),
    ]
