# Generated by Django 4.2.25 on 2025-10-17 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='fullscreen_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='max_violations_allowed',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='proctoring_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='examinvitation',
            name='access_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='examinvitation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='examinvitation',
            name='max_attempts',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='examinvitation',
            name='used_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examinvitation',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examinvitation',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ExamViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('tab_switch', 'Tab Switch'), ('window_blur', 'Window Lost Focus'), ('multiple_faces', 'Multiple Faces Detected'), ('no_face', 'No Face Detected'), ('looking_away', 'Looking Away'), ('mobile_detected', 'Mobile Phone Detected'), ('copy_paste', 'Copy/Paste Attempt'), ('fullscreen_exit', 'Exited Fullscreen')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='violations/')),
                ('metadata', models.JSONField(default=dict, help_text='Store detection confidence, etc.')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='exams.examattempt')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ExamProctoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webcam_enabled', models.BooleanField(default=False)),
                ('snapshots', models.JSONField(default=list, help_text='List of snapshot URLs with timestamps')),
                ('face_verification_passed', models.BooleanField(default=False)),
                ('total_violations', models.IntegerField(default=0)),
                ('auto_disqualified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proctoring', to='exams.examattempt')),
            ],
        ),
    ]
