# Generated by Django 4.2.25 on 2025-10-21 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_alter_examviolation_violation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examviolation',
            name='violation_type',
            field=models.CharField(choices=[('tab_switch', 'Tab Switch'), ('window_blur', 'Window Lost Focus'), ('multiple_faces', 'Multiple Faces Detected'), ('no_face', 'No Face Detected'), ('looking_away', 'Looking Away'), ('mobile_detected', 'Mobile Phone Detected'), ('copy_paste', 'Copy/Paste Attempt'), ('fullscreen_exit', 'Exited Fullscreen'), ('fullscreen_error', 'Fullscreen Error'), ('right_click', 'Right Click Attempt'), ('keyboard_shortcut', 'Keyboard Shortcut Attempt')], max_length=20),
        ),
    ]
