# Generated by Django 4.2.25 on 2025-10-23 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_alter_examviolation_violation_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('question_text', models.TextField()),
                ('total_attempts', models.IntegerField(default=0)),
                ('correct_attempts', models.IntegerField(default=0)),
                ('wrong_attempts', models.IntegerField(default=0)),
                ('unattempted', models.IntegerField(default=0)),
                ('average_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('max_marks', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_analytics', to='exams.exam')),
            ],
            options={
                'ordering': ['question_number'],
                'unique_together': {('exam', 'question_number')},
            },
        ),
    ]
