# Generated by Django 4.2.25 on 2025-10-27 19:23

from django.db import migrations, models
from django.db.models import deletion
from django.core.validators import MinValueValidator
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_add_evaluation_models'),
    ]

    operations = [
        # Add new fields to Exam model
        migrations.AddField(
            model_name='exam',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
        migrations.AddField(
            model_name='exam',
            name='grace_period_minutes',
            field=models.IntegerField(default=0, help_text='Extra time after end_date'),
        ),
        migrations.AddField(
            model_name='exam',
            name='buffer_time_minutes',
            field=models.IntegerField(default=15, help_text='Time before exam starts when students can access'),
        ),
        migrations.AddField(
            model_name='exam',
            name='auto_start',
            field=models.BooleanField(default=True, help_text='Automatically start exam at start_date'),
        ),
        migrations.AddField(
            model_name='exam',
            name='auto_end',
            field=models.BooleanField(default=True, help_text='Automatically end exam at end_date'),
        ),
        migrations.AddField(
            model_name='exam',
            name='reschedule_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='max_reschedules',
            field=models.IntegerField(default=0, validators=[MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='exam',
            name='reschedule_deadline',
            field=models.DateTimeField(blank=True, help_text='Last date when rescheduling is allowed', null=True),
        ),
        
        # Create ExamReschedule model
        migrations.CreateModel(
            name='ExamReschedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_start_date', models.DateTimeField()),
                ('original_end_date', models.DateTimeField()),
                ('new_start_date', models.DateTimeField()),
                ('new_end_date', models.DateTimeField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('exam', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='reschedules', to='exams.exam')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, related_name='reviewed_reschedules', to='accounts.user')),
                ('student', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='exam_reschedules', to='accounts.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='examreschedule',
            constraint=models.UniqueConstraint(fields=('exam', 'student', 'status'), name='unique_pending_reschedule'),
        ),
        
        # Add only missing fields to ExamInvitation model
        migrations.AddField(
            model_name='examinvitation',
            name='invitation_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='examinvitation',
            name='custom_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='examinvitation',
            name='decline_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='examinvitation',
            name='declined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examinvitation',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.deletion.CASCADE, related_name='student_invitations', to='accounts.user'),
        ),
    ]
