# Generated by Django 4.2.25 on 2025-10-29 07:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0007_auto_20251027_1923'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='examreschedule',
            name='unique_pending_reschedule',
        ),
        migrations.AddField(
            model_name='examinvitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='examreschedule',
            unique_together={('exam', 'student', 'status')},
        ),
    ]
