# Generated by Django 4.2.25 on 2025-11-05 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_remove_examreschedule_unique_pending_reschedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='answers',
            field=models.JSONField(blank=True, default=dict, help_text='Student answers during exam (auto-saved)'),
        ),
    ]
