# Generated by Django 4.2.25 on 2025-11-09 16:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


def generate_public_access_tokens(apps, schema_editor):
    Exam = apps.get_model('exams', 'Exam')
    for exam in Exam.objects.all():
        exam.public_access_token = uuid.uuid4()
        if exam.public_link_created_at is None:
            exam.public_link_created_at = django.utils.timezone.now()
        exam.save(update_fields=['public_access_token', 'public_link_created_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_adjust_exam_status_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='public_access_token',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='public_allow_multiple_devices',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='public_allowed_ip_ranges',
            field=models.JSONField(blank=True, default=list, help_text='List of allowed IPv4 / IPv6 addresses or CIDR ranges'),
        ),
        migrations.AddField(
            model_name='exam',
            name='public_link_created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='exam',
            name='public_link_last_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='public_link_usage_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exam',
            name='public_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(generate_public_access_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='exam',
            name='public_access_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PublicExamAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.UUIDField()),
                ('status', models.CharField(choices=[('granted', 'Granted'), ('denied', 'Denied')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('student_email', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_access_logs', to='exams.exam')),
            ],
            options={
                'ordering': ['-accessed_at'],
            },
        ),
    ]
