# Generated by Django 4.2.25 on 2025-11-17 10:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0011_exam_public_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='answer_sheet_pdf',
            field=models.FileField(blank=True, null=True, upload_to='answer_sheets/'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='public_access_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
