# Generated by Django 4.2.25 on 2025-11-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0012_examattempt_answer_sheet_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='answer_sheet_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
