# Generated by Django 4.2.25 on 2025-12-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0014_examproctoring_incidents'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='shuffle_options',
            field=models.BooleanField(default=False, help_text='Shuffle MCQ options for each question'),
        ),
        migrations.AddField(
            model_name='exam',
            name='shuffle_questions',
            field=models.BooleanField(default=False, help_text='Enable question shuffling for students'),
        ),
        migrations.AddField(
            model_name='exam',
            name='shuffle_sections',
            field=models.BooleanField(default=False, help_text='Shuffle the order of sections'),
        ),
        migrations.AddField(
            model_name='exam',
            name='shuffle_seed_per_student',
            field=models.BooleanField(default=True, help_text='Use different shuffle order for each student'),
        ),
        migrations.AddField(
            model_name='exam',
            name='shuffle_subjects',
            field=models.BooleanField(default=False, help_text='Shuffle the order of subjects'),
        ),
        migrations.AddField(
            model_name='exam',
            name='shuffle_within_sections',
            field=models.BooleanField(default=True, help_text='Shuffle questions within each section'),
        ),
    ]
