# Generated by Django 4.2.16 on 2026-01-22 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0015_add_shuffle_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='geolocation_captured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='geolocation_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='geolocation_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='geolocation_permission_denied',
            field=models.BooleanField(default=False),
        ),
    ]
