# Generated by Django 4.2.16 on 2026-01-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_role_activitylog'),
        ('exams', '0016_add_geolocation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='allowed_batches',
            field=models.ManyToManyField(blank=True, help_text="Batches whose students can access this exam (when visibility_scope='batches')", related_name='exams', to='accounts.batch'),
        ),
        migrations.AddField(
            model_name='exam',
            name='allowed_centers',
            field=models.ManyToManyField(blank=True, help_text="Centers whose students can access this exam (when visibility_scope='centers')", related_name='exams', to='accounts.center'),
        ),
        migrations.AddField(
            model_name='exam',
            name='visibility_scope',
            field=models.CharField(choices=[('institute', 'Institute-Wide'), ('centers', 'Specific Centers'), ('batches', 'Specific Batches')], default='institute', help_text='Controls which students can access this exam', max_length=20),
        ),
    ]
