# Generated by Django 4.2.16 on 2026-01-31 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0017_add_visibility_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examproctoring',
            name='snapshots',
            field=models.JSONField(default=list, help_text='List of snapshot metadata with timestamps (Base64 images removed)'),
        ),
        migrations.CreateModel(
            name='ProctoringSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='proctoring_snapshots/')),
                ('timestamp', models.DateTimeField()),
                ('metadata', models.JSONField(default=dict)),
                ('analysis', models.JSONField(default=dict)),
                ('has_violations', models.BooleanField(default=False)),
                ('stored_reason', models.CharField(default='monitoring', max_length=50)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctoring_snapshot_files', to='exams.examattempt')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
