# Generated by Django 4.2.16 on 2026-02-05 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_make_program_institute_required'),
        ('exams', '0018_alter_examproctoring_snapshots_proctoringsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='ai_evaluation_enabled',
            field=models.BooleanField(default=False, help_text='Enable AI-powered evaluation for subjective answers'),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_mode',
            field=models.CharField(choices=[('online', 'Online Exam'), ('offline_omr', 'Offline OMR-Based'), ('offline_subjective', 'Offline Subjective')], default='online', help_text='How the exam is conducted: online (in-app), offline_omr (OMR sheets), offline_subjective (handwritten answers)', max_length=20),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_scope',
            field=models.CharField(choices=[('exam_specific', 'Exam-Specific Questions'), ('program_specific', 'Program-Specific Questions')], default='exam_specific', help_text='Whether exam uses its own questions or program-level questions', max_length=20),
        ),
        migrations.AddField(
            model_name='exam',
            name='marking_strictness',
            field=models.CharField(choices=[('lenient', 'Lenient'), ('moderate', 'Moderate'), ('strict', 'Strict')], default='moderate', help_text='How strict the AI grading should be', max_length=20),
        ),
        migrations.AddField(
            model_name='exam',
            name='omr_config',
            field=models.JSONField(blank=True, default=dict, help_text='OMR sheet configuration (candidate fields, question types, etc.)'),
        ),
        migrations.AddField(
            model_name='exam',
            name='omr_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Generated OMR layout metadata for evaluation'),
        ),
        migrations.AddField(
            model_name='exam',
            name='omr_sheet_file',
            field=models.FileField(blank=True, help_text='Generated OMR sheet PDF file', null=True, upload_to='omr_sheets/'),
        ),
        migrations.AddField(
            model_name='exam',
            name='omr_sheet_generated',
            field=models.BooleanField(default=False, help_text='Whether OMR sheet has been generated for this exam'),
        ),
        migrations.AddField(
            model_name='exam',
            name='program',
            field=models.ForeignKey(blank=True, help_text='Program this exam belongs to (for program-specific exams)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='accounts.program'),
        ),
    ]
