# Generated by Django 4.2.16 on 2026-02-07 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0019_add_exam_mode_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_mode',
            field=models.CharField(choices=[('online', 'Online Exam'), ('offline_omr', 'Offline OMR-Based'), ('offline_subjective', 'Offline Subjective'), ('hybrid', 'Hybrid (Online + Offline)')], default='online', help_text='How the exam is conducted: online (in-app), offline_omr (OMR sheets), offline_subjective (handwritten answers), hybrid (combination)', max_length=20),
        ),
    ]
