# Generated by Django 4.2.7 on 2026-03-10 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0013_institute_db_host_institute_db_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("exams", "0020_add_hybrid_exam_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="allowed_batches",
            field=models.ManyToManyField(
                blank=True,
                db_constraint=False,
                help_text="Batches whose students can access this exam (when visibility_scope='batches')",
                related_name="exams",
                to="accounts.batch",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="allowed_centers",
            field=models.ManyToManyField(
                blank=True,
                db_constraint=False,
                help_text="Centers whose students can access this exam (when visibility_scope='centers')",
                related_name="exams",
                to="accounts.center",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="allowed_users",
            field=models.ManyToManyField(
                blank=True,
                db_constraint=False,
                related_name="allowed_exams",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="created_by",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_exams",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="institute",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exams",
                to="accounts.institute",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="program",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Program this exam belongs to (for program-specific exams)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="exams",
                to="accounts.program",
            ),
        ),
        migrations.AlterField(
            model_name="examattempt",
            name="student",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exam_attempts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="examinvitation",
            name="invited_by",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_invitations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="examinvitation",
            name="student",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_invitations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="examinvitation",
            name="user",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exam_invitations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="examreschedule",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_reschedules",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="questionevaluation",
            name="evaluated_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="evaluated_questions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
