# Generated by Django 4.2.25 on 2026-03-12 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0016_program_center"),
        ("exams", "0021_alter_exam_allowed_batches_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="center",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Center this exam belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_exams",
                to="accounts.center",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="visibility_scope",
            field=models.CharField(
                choices=[
                    ("institute", "Institute-Wide"),
                    ("centers", "Specific Centers"),
                    ("batches", "Specific Batches"),
                    ("program", "Specific Program"),
                ],
                default="institute",
                help_text="Controls which students can access this exam",
                max_length=20,
            ),
        ),
    ]
