# Generated by Django 5.2.9 on 2025-12-16 05:04

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Timetable",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_date",
                    models.DateField(
                        help_text="Start date of the timetable period. Example: 2025-01-01"
                    ),
                ),
                (
                    "to_date",
                    models.DateField(
                        help_text="End date of the timetable period. Example: 2025-03-31"
                    ),
                ),
                (
                    "free_classes_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of free classes in this timetable. Example: If set to 3, then the first 3 classes are marked as free.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this timetable is currently active.",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description or notes about this timetable.",
                    ),
                ),
                (
                    "center",
                    models.ForeignKey(
                        help_text="Center for which this timetable is created.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetables",
                        to="accounts.center",
                    ),
                ),
            ],
            options={
                "verbose_name": "Timetable",
                "verbose_name_plural": "Timetables",
                "ordering": ["-from_date", "-to_date"],
            },
        ),
        migrations.CreateModel(
            name="DaySlot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("MON", "Monday"),
                            ("TUE", "Tuesday"),
                            ("WED", "Wednesday"),
                            ("THU", "Thursday"),
                            ("FRI", "Friday"),
                            ("SAT", "Saturday"),
                            ("SUN", "Sunday"),
                        ],
                        help_text="Day of the week (Monday, Tuesday, etc.).",
                        max_length=3,
                    ),
                ),
                (
                    "slot_number",
                    models.PositiveIntegerField(
                        help_text="Slot number for this day. Example: 1 for first class, 2 for second class, etc.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(
                        help_text="Start time of this class slot. Example: 08:00"
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(
                        help_text="End time of this class slot. Example: 09:00"
                    ),
                ),
                (
                    "is_free_class",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this slot is a free class. This is automatically set based on free_classes_count in Timetable.",
                    ),
                ),
                (
                    "timetable",
                    models.ForeignKey(
                        help_text="Timetable to which this day slot belongs.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="day_slots",
                        to="timetable.timetable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Day Slot",
                "verbose_name_plural": "Day Slots",
                "ordering": ["timetable", "day", "slot_number"],
                "unique_together": {("timetable", "day", "slot_number")},
            },
        ),
        migrations.CreateModel(
            name="TeacherConstraint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "min_classes",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Minimum number of classes this teacher must teach per week.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "max_classes",
                    models.PositiveIntegerField(
                        help_text="Maximum number of classes this teacher can teach per week.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        help_text="Teacher for whom this constraint is set.",
                        limit_choices_to={"role": "TEACHER"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_constraints",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "timetable",
                    models.ForeignKey(
                        help_text="Timetable for which this constraint applies.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_constraints",
                        to="timetable.timetable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Teacher Constraint",
                "verbose_name_plural": "Teacher Constraints",
                "ordering": ["timetable", "teacher__username"],
                "unique_together": {("timetable", "teacher")},
            },
        ),
        migrations.CreateModel(
            name="TeacherAvailability",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "date",
                    models.DateField(
                        help_text="Date for which availability is being tracked."
                    ),
                ),
                (
                    "is_present",
                    models.BooleanField(
                        default=True,
                        help_text="True if teacher is present, False if absent.",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text="Optional reason for absence (if is_present = False).",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        help_text="Teacher whose availability is being tracked.",
                        limit_choices_to={"role": "TEACHER"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_availabilities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "timetable",
                    models.ForeignKey(
                        help_text="Timetable for which this availability is tracked.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_availabilities",
                        to="timetable.timetable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Teacher Availability",
                "verbose_name_plural": "Teacher Availabilities",
                "ordering": ["date", "teacher__username"],
                "unique_together": {("timetable", "teacher", "date")},
            },
        ),
        migrations.CreateModel(
            name="TimetableEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subject",
                    models.CharField(
                        help_text="Subject being taught. Example: 'Physics', 'Chemistry', 'Maths'.",
                        max_length=100,
                    ),
                ),
                (
                    "room_number",
                    models.CharField(
                        blank=True,
                        help_text="Optional room number or location where this class will be held.",
                        max_length=50,
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        help_text="Batch that will have class in this slot.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_entries",
                        to="accounts.batch",
                    ),
                ),
                (
                    "day_slot",
                    models.ForeignKey(
                        help_text="Day slot for which this entry is created.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_entries",
                        to="timetable.dayslot",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        help_text="Teacher who will teach this class.",
                        limit_choices_to={"role": "TEACHER"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="timetable_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Timetable Entry",
                "verbose_name_plural": "Timetable Entries",
                "ordering": ["day_slot__day", "day_slot__slot_number", "batch__code"],
                "unique_together": {("day_slot", "batch")},
            },
        ),
    ]
