# Generated by Django 5.2.9 on 2025-12-16 07:31

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_center_alter_user_options_and_more"),  # Use migration that creates Center, Program, Batch models
        ("timetable", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dayslot",
            name="slot_code",
            field=models.CharField(
                blank=True,
                help_text="Short code for this day-slot, e.g. 'm1', 'tu3', 'w5'.",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="BatchFacultyLoad",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "total_lectures",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Planned number of lectures for this teacher in this batch.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "min_lectures_per_day",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Minimum number of lectures per day for this teacher in this batch.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "max_lectures_per_day",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Maximum number of lectures per day for this teacher in this batch.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        help_text="Batch to which this load configuration applies.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faculty_loads",
                        to="accounts.batch",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        help_text="Faculty / teacher.",
                        limit_choices_to={"role": "TEACHER"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batch_faculty_loads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "timetable",
                    models.ForeignKey(
                        help_text="Timetable for which this faculty load is defined.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batch_faculty_loads",
                        to="timetable.timetable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Batch Faculty Load",
                "verbose_name_plural": "Batch Faculty Loads",
                "ordering": ["batch__code", "teacher__username"],
                "unique_together": {("timetable", "teacher", "batch")},
            },
        ),
        migrations.CreateModel(
            name="FixedSlot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        help_text="Subject code/name for this fixed slot. Leave empty if this is a free / exam / non-teaching slot.",
                        max_length=100,
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(
                        default=True,
                        help_text="If true, this slot is locked and cannot be modified by automatic timetable generation logic.",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        help_text="Batch affected by this fixed slot.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fixed_slots",
                        to="accounts.batch",
                    ),
                ),
                (
                    "day_slot",
                    models.ForeignKey(
                        help_text="Specific day + slot that is fixed.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fixed_slots",
                        to="timetable.dayslot",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        help_text="Teacher code for this fixed slot (optional if free/exam).",
                        limit_choices_to={"role": "TEACHER"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fixed_slots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "timetable",
                    models.ForeignKey(
                        help_text="Timetable this fixed slot belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fixed_slots",
                        to="timetable.timetable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fixed Slot",
                "verbose_name_plural": "Fixed Slots",
                "ordering": ["day_slot__day", "day_slot__slot_number", "batch__code"],
                "unique_together": {("timetable", "day_slot", "batch")},
            },
        ),
        migrations.CreateModel(
            name="TeacherSlotAvailability",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_available",
                    models.BooleanField(
                        default=True,
                        help_text="True if the teacher is available in this slot; False if blocked.",
                    ),
                ),
                (
                    "day_slot",
                    models.ForeignKey(
                        help_text="Specific day + slot (e.g. Monday m1) for this availability.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_availabilities",
                        to="timetable.dayslot",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        help_text="Teacher whose weekly slot availability this record describes.",
                        limit_choices_to={"role": "TEACHER"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_slot_availabilities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "timetable",
                    models.ForeignKey(
                        help_text="Timetable (date range) this weekly availability pattern belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_teacher_availabilities",
                        to="timetable.timetable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Teacher Slot Availability",
                "verbose_name_plural": "Teacher Slot Availabilities",
                "ordering": [
                    "teacher__username",
                    "day_slot__day",
                    "day_slot__slot_number",
                ],
                "unique_together": {("timetable", "teacher", "day_slot")},
            },
        ),
    ]
