# Generated by Django 5.2.9 on 2025-12-16 08:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timetable", "0002_dayslot_slot_code_batchfacultyload_fixedslot_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timetableentry",
            name="teacher",
        ),
        migrations.AddField(
            model_name="batchfacultyload",
            name="free_lectures",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of free/demo lectures for this teacher in this batch. Set when assigning teacher to the batch.",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
