# Generated by Django 5.2.9 on 2025-12-16 13:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timetable", "0003_remove_timetableentry_teacher_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimetableHoliday",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(help_text="Calendar date of the holiday.")),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Optional description, e.g. 'Independence Day', 'Exam Day'.",
                        max_length=255,
                    ),
                ),
                (
                    "is_full_day",
                    models.BooleanField(
                        default=True,
                        help_text="True if entire day is holiday; False if partial (handled by slots).",
                    ),
                ),
                (
                    "timetable",
                    models.ForeignKey(
                        help_text="Timetable this holiday belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holidays",
                        to="timetable.timetable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Timetable Holiday",
                "verbose_name_plural": "Timetable Holidays",
                "ordering": ["date"],
                "unique_together": {("timetable", "date")},
            },
        ),
    ]
