# Generated by Django 5.2.9 on 2025-12-17 06:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timetable", "0004_timetableholiday"),
    ]

    operations = [
        migrations.AddField(
            model_name="batchfacultyload",
            name="max_lectures_per_week",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Maximum number of lectures per week for this teacher in this batch.",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="batchfacultyload",
            name="max_lectures_per_day",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Maximum number of lectures per day for this teacher in this batch.",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
