# Generated by Django 4.2.7 on 2025-12-17 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("timetable", "0005_batchfacultyload_max_lectures_per_week_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batchfacultyload",
            name="teacher",
            field=models.ForeignKey(
                help_text="Faculty / teacher.",
                limit_choices_to={"role": "teacher"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="batch_faculty_loads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="fixedslot",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                help_text="Teacher code for this fixed slot (optional if free/exam).",
                limit_choices_to={"role": "teacher"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fixed_slots",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="teacheravailability",
            name="teacher",
            field=models.ForeignKey(
                help_text="Teacher whose availability is being tracked.",
                limit_choices_to={"role": "teacher"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_availabilities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="teacherconstraint",
            name="teacher",
            field=models.ForeignKey(
                help_text="Teacher for whom this constraint is set.",
                limit_choices_to={"role": "teacher"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_constraints",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="teacherslotavailability",
            name="teacher",
            field=models.ForeignKey(
                help_text="Teacher whose weekly slot availability this record describes.",
                limit_choices_to={"role": "teacher"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="weekly_slot_availabilities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
