# Generated by Django 4.2.7 on 2025-12-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timetable", "0006_alter_batchfacultyload_teacher_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dayslot",
            name="actual_date",
            field=models.DateField(
                blank=True,
                help_text="Concrete calendar date for this slot. Used for date-based timetables. For legacy weekly timetables this may be null.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="dayslot",
            name="day_index",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Index of the calendar day within the timetable date range, starting at 1. Example: D1 = from_date, D2 = from_date + 1 day, etc.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="dayslot",
            name="day",
            field=models.CharField(
                choices=[
                    ("MON", "Monday"),
                    ("TUE", "Tuesday"),
                    ("WED", "Wednesday"),
                    ("THU", "Thursday"),
                    ("FRI", "Friday"),
                    ("SAT", "Saturday"),
                    ("SUN", "Sunday"),
                ],
                help_text="Day of the week (Monday, Tuesday, etc.) for legacy weekly timetables. For date-based timetables that use D1..Dn, this is derived from actual_date.",
                max_length=3,
            ),
        ),
    ]
