# Generated by Django 4.2.7 on 2025-12-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timetable", "0007_dayslot_actual_date_dayslot_day_index_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dayslot",
            options={
                "ordering": ["timetable", "day_index", "day", "slot_number"],
                "verbose_name": "Day Slot",
                "verbose_name_plural": "Day Slots",
            },
        ),
        migrations.AlterUniqueTogether(
            name="dayslot",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="dayslot",
            name="day",
            field=models.CharField(
                blank=True,
                help_text="Day of the week (MON, TUE, etc.) for legacy weekly timetables. For date-based timetables, this is derived from actual_date. Can be null for date-based timetables where day_index is used.",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="dayslot",
            index=models.Index(
                fields=["timetable", "day_index", "slot_number"],
                name="timetable_d_timetab_6a97f3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dayslot",
            index=models.Index(
                fields=["timetable", "day", "slot_number"],
                name="timetable_d_timetab_6f7b1e_idx",
            ),
        ),
    ]
