# Generated by Django 4.2.7 on 2025-12-19 11:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_make_batch_program_optional"),
        ("timetable", "0008_support_unlimited_days"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimetableBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "batch",
                    models.ForeignKey(
                        help_text="Batch assigned to the timetable.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_assignments",
                        to="accounts.batch",
                    ),
                ),
                (
                    "timetable",
                    models.ForeignKey(
                        help_text="Timetable to which this batch is assigned.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_batches",
                        to="timetable.timetable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Timetable Batch",
                "verbose_name_plural": "Timetable Batches",
                "ordering": ["batch__code"],
                "unique_together": {("timetable", "batch")},
            },
        ),
    ]
