# Generated by Django 4.2.7 on 2025-12-20 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("timetable", "0009_add_timetable_batch"),
    ]

    operations = [
        migrations.AddField(
            model_name="timetableentry",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                help_text="Teacher assigned to this slot (from optimization).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="timetable_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
