# Generated by Django 4.2.7 on 2025-12-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timetable", "0010_add_teacher_to_timetable_entry"),
    ]

    operations = [
        migrations.AddField(
            model_name="timetable",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Name of the timetable. Example: 'JEE Main 2025 Schedule'",
                max_length=255,
            ),
        ),
    ]
