# Generated by Django 4.2.7 on 2025-12-22 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("timetable", "0011_add_timetable_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="batchfacultyload",
            name="subject_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Subject name. Used for FREE, Exam, or when teacher is null.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="batchfacultyload",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                help_text="Faculty / teacher. Null for special entries like FREE, Exam.",
                limit_choices_to={"role": "teacher"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="batch_faculty_loads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
