# Generated by Django 4.2.7 on 2025-12-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timetable", "0012_add_nullable_teacher_and_subject_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timetable",
            name="is_active",
            field=models.BooleanField(
                default=False, help_text="Whether this timetable is currently active."
            ),
        ),
    ]
