# Generated by Django 4.2.7 on 2026-03-10 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0013_institute_db_host_institute_db_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("timetable", "0013_change_is_active_default_to_false"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batchfacultyload",
            name="batch",
            field=models.ForeignKey(
                db_constraint=False,
                help_text="Batch to which this load configuration applies.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="faculty_loads",
                to="accounts.batch",
            ),
        ),
        migrations.AlterField(
            model_name="batchfacultyload",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Faculty / teacher. Null for special entries like FREE, Exam.",
                limit_choices_to={"role": "teacher"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="batch_faculty_loads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="fixedslot",
            name="batch",
            field=models.ForeignKey(
                db_constraint=False,
                help_text="Batch affected by this fixed slot.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fixed_slots",
                to="accounts.batch",
            ),
        ),
        migrations.AlterField(
            model_name="fixedslot",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Teacher code for this fixed slot (optional if free/exam).",
                limit_choices_to={"role": "teacher"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fixed_slots",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="teacheravailability",
            name="teacher",
            field=models.ForeignKey(
                db_constraint=False,
                help_text="Teacher whose availability is being tracked.",
                limit_choices_to={"role": "teacher"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_availabilities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="teacherconstraint",
            name="teacher",
            field=models.ForeignKey(
                db_constraint=False,
                help_text="Teacher for whom this constraint is set.",
                limit_choices_to={"role": "teacher"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_constraints",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="teacherslotavailability",
            name="teacher",
            field=models.ForeignKey(
                db_constraint=False,
                help_text="Teacher whose weekly slot availability this record describes.",
                limit_choices_to={"role": "teacher"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="weekly_slot_availabilities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="timetable",
            name="center",
            field=models.ForeignKey(
                db_constraint=False,
                help_text="Center for which this timetable is created.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timetables",
                to="accounts.center",
            ),
        ),
        migrations.AlterField(
            model_name="timetablebatch",
            name="batch",
            field=models.ForeignKey(
                db_constraint=False,
                help_text="Batch assigned to the timetable.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timetable_assignments",
                to="accounts.batch",
            ),
        ),
        migrations.AlterField(
            model_name="timetableentry",
            name="batch",
            field=models.ForeignKey(
                db_constraint=False,
                help_text="Batch that will have class in this slot.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timetable_entries",
                to="accounts.batch",
            ),
        ),
        migrations.AlterField(
            model_name="timetableentry",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Teacher assigned to this slot (from optimization).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="timetable_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
